### ISSUE TITLE
Graph data issue

### ISSUE THREAD

**Issue by Albinzr** [CoinCircle/go-coinmarketcap#2]
I'm not able to get get the graph data always getting empty result Can you give an example of passing params with a URL to check in browser

**Comment by miguelmota** [comment]
@Albinzr here's the graph url endpoint to get all the data points

https://graphs.coinmarketcap.com/currencies/ethereum/

here's an example of passing start and end timestamps (unix time in milliseconds)

https://graphs.coinmarketcap.com/currencies/ethereum/1515511616471/1515521562844/

Hope this helps
